### ISSUE TITLE
SignUp Issue

### ISSUE THREAD

**Issue by gauravgrover95** [sdslabs/jinora#39] opened 2016-03-13 17:36 UTC
It seems login/SignUp mechanism for the Jinora needs a fix.  I just pressed "Esc" instead of entering a username for the chat and It still took me to the chat. At first I thought it is fine, maybe it won't let me post anything but when I tried to message something I found that it has given me some random name and prompted me that I cant use that name. and when I clicked OK, it posted my message with the same random name. Below are some screenshots: 

[http://imgur.com/a/u3as5](url)

**Comment by apsdehal** [comment] 2016-03-13 18:28
Can you open a PR for this also, it is an easy fix. Also the thing works for me, I have tried three. Try again, if it happens also provide the random username assigned. Closing because unable to reproduce. Reopen if you feel so.

**Closed by apsdehal** 2016-03-13 18:28 UTC
